# Generated by Django 5.0.7 on 2024-07-17 20:36

import accounts.models
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="birth",
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
